---
$ANSIBLE_VAULT;1.1;AES256
64343536663565626535643638336462373539633738616166323938383234333434306338396131
6230653232643336386537623535666636393762353834620a636663656239666631346139363032
64336166626136336332386339663565323733393739623366643631646364323438373165303130
3531383935643935650a376461303238383738646263656561636239393034613539396331323137
66663635346164623562623864643666643738373332363535333866643934613865343461663437
33626635643265393138333834343165383537366564303032663938663036623262383830323734
65333438633431616330366331353335343236383030363133656161363631666165343832663838
33396630633933366339666637323131333930323433393737656139613564643365373662616665
31313834383035646664343166333764316662346631373536383339386232373336616432346530
39393865383362303863306563626461633533326637343438393833343863323636343866356335
38623938356134343465666433643038616631333264393836306631633032343566626535643339
36636434343362373266356462356332666531303433383964323630333434336162636335373036
39383662333237663239323261633861643333393061376662616465666631653835616334663133
61333235336633316231383133323934616234363739643130383631383534653764323731346562
65363831613931346331636436333166613464636538636335393534666538656365393839383664
65363266373636396261613639633336646530353934383231613763303162306539353631636666
36356434663636303765383462626236663736356465633136323835333561323964366562333461
63643366306539643863303633366530663066633139663261316662393937316261343933333362
616137323936653233653664343436376434
